version: '3.4'

services:
  codeflows.workspace:
    env_file: "Dockerfile.env"
    volumes:
      - repository-volume:/app/repos

  codeflows.csharp:
    image: ${DOCKER_REGISTRY-}codeflowscsharp
    volumes:
      - repository-volume:/app/global-repos
      - csharp-repository-volume:/app/my-repos
      - csharp-tools-volume:/app/tools

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  csharp-tools-volume:
  repository-volume:
    driver: local  
  csharp-repository-volume:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: