version: '3.4'

services:
  codeflows.workspace:
    image: ${DOCKER_REGISTRY-}codeflowsworkspace
    build:
      context: .
      dockerfile: CodeFlows.Workspace/Dockerfile

  codeflows.csharp:
    image: ${DOCKER_REGISTRY-}codeflowscsharp
    build:
      context: .
      dockerfile: Codeflows.Csharp/Dockerfile

