version: '3.4'

services:
  codeflows.workspace:
    image: ${DOCKER_REGISTRY-}codeflowsworkspace
    build:
      context: .
      dockerfile: CodeFlows.Workspace/Dockerfile

  codeflows.csharp:
    image: ${DOCKER_REGISTRY-}codeflowscsharp
    build:
      context: .
      dockerfile: Codeflows.Csharp/Dockerfile


  codeflows.genai:
    image: ${DOCKER_REGISTRY-}codeflowsgenai
    build:
      context: .
      dockerfile: CodeFlows.GenAi/Dockerfile


  codeflows.workflowdeployer:
    image: ${DOCKER_REGISTRY-}codeflowsworkflowdeployer
    build:
      context: .
      dockerfile: Codeflows.WorkflowDeployer/Dockerfile


  codeflows.portal:
    image: ${DOCKER_REGISTRY-}codeflowsportal
    build:
      context: .
      dockerfile: Codeflows.Portal/Dockerfile

